app/Http/routes.php
<?php


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('auth/connexion', 'Auth\AuthController@getLogin');
Route::post('auth/connexion', 'Auth\AuthController@postLogin');
Route::get('auth/deconnexion', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/inscription', 'Auth\AuthController@getRegister');
Route::post('auth/inscription', 'Auth\AuthController@postRegister');


// Users route
Route::get('/api/users', 'AccountController@getUsers');
Route::get('/api/evenements/titles', 'EventsController@getTitles');
Route::get('/api/evenements', 'EventsController@getEventsSortByStatus');

// Account routes...
Route::get('/account', 'AccountController@edit')->middleware('auth');
Route::post('/account/{user}', 'AccountController@update')->middleware('auth');
Route::delete('/account/{id}', 'AccountController@destroy')->middleware('auth');

Route::get('/', 'PagesController@index');

Route::get('/evenements', 'EventsController@index');
Route::get('/evenements/recherche_avancee', 'EventsController@advancedSearch');
Route::post('/evenements/rechercher', 'EventsController@search');
Route::get('/evenements/rechercher/tag/{tag}', 'EventsController@searchByTag');
Route::get('/evenements/titles', 'EventsController@getTitles');

Route::get('/evenements/agenda', 'EventsController@showAgenda');
Route::get('/evenements/ajouter', 'EventsController@create')->middleware('auth');
Route::get('/evenements/validates/{id}', 'EventsController@validatesEvent')->middleware('auth');
Route::post('/evenements/ajouter', 'EventsController@store')->name('events.store')->middleware('auth');
Route::get('/evenements/{id}', 'EventsController@show');
Route::get('/evenements/{id}/modifier', 'EventsController@edit')->middleware('auth');
Route::post('/evenements/{id}/modifier', 'EventsController@update')->middleware('auth')->name('events.update');
Route::get('/evenements/{id}/tags', 'EventsController@getTagsJson');

Route::get('/gpscoords', 'EventsController@eventsWithCoordinates');


Route::get('/admin', 'AdminController@index')->middleware('auth');
Route::get('/admin/users', 'AdminController@users')->middleware('auth');
Route::get('/admin/events', 'AdminController@events')->middleware('auth');

Route::get('/contact', 'PagesController@contact');
Route::get('/mentions-legales', 'PagesController@legalMentions');

/**
 * Security to avoid route crash for some defaults redirects
 */
Route::get('/home', function() {
    return redirect('/');
});

Route::get('/test_email', 'EmailTestController@index');

Route::resource('alertes', 'AlertsController', ['except' => ['show', 'create', 'update', 'edit']]);
Route::post('avis/add', 'OpinionsController@store')->name('opinion.store');
Route::get('alertes/table', 'AlertsController@getHtmlTableListingAlerts');

Route::get("/sitemap", function(){
    // create new sitemap object
    $sitemap = App::make("sitemap");

    // set cache key (string), duration in minutes (Carbon|Datetime|int), turn on/off (boolean)
    // by default cache is disabled
    $sitemap->setCache('laravel.sitemap', 180);

    // check if there is cached sitemap and build new only if is not
    if (!$sitemap->isCached())
    {
        // add item to the sitemap (url, date, priority, freq)
        $sitemap->add(url('/'), date('c'), '1.0', 'daily');
        $sitemap->add(url('/auth/connexion'), date('c'), '0.5', 'monthly');
        $sitemap->add(url('/auth/inscription'), date('c'), '0.5', 'monthly');
        $sitemap->add(url('/account'), date('c'), '0.7', 'monthly');
        $sitemap->add(url('/evenements'), date('c'), '1.0', 'monthly');
        $sitemap->add(url('/evenements/rechercher'), date('c'), '0.8', 'monthly');
        $sitemap->add(url('/evenements/recherche_avancee'), date('c'), '0.8', 'monthly');
        $sitemap->add(url('/evenements/agenda'), date('c'), '0.9', 'monthly');
        $sitemap->add(url('/evenements/ajouter'), date('c'), '0.7', 'monthly');
        $sitemap->add(url('/contact'), date('c'), '0.6', 'monthly');
        $sitemap->add(url('/mentions-legales'), date('c'), '0.5', 'monthly');

    }

    // show your sitemap (options: 'xml' (default), 'html', 'txt', 'ror-rss', 'ror-rdf')
    return $sitemap->render('xml');
});

app/Alert.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

class Alert extends Model
{
    /**
     * @param User
     * @return Collection
     */
    public static function allOfUser($user)
    {
        return Alert::where('user_id', $user->id)->get();
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function event() {
        return $this->belongsTo('App\Event');
    }

    public function getDateAttribute() {
        $date = new Carbon($this->event->begin_date);
        return $date->subDays($this->days_before)->format('d/m/y');
    }

    protected $fillable = ['days_before', 'user_id', 'event_id'];
}

app/Http/Controllers/AlertsController.php
<?php

namespace App\Http\Controllers;

use App\Alert;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;


use App\Http\Requests;

class AlertsController extends Controller
{
    /**
     * AlertsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $alerts = Alert::allOfUser(\Auth::user());
        return view('alerts.index')->with(compact('alerts'));
    }

    public function getHtmlTableListingAlerts(){
        $alerts = Alert::allOfUser(\Auth::user());
        return view('alerts.table')->with(compact('alerts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @internal param int $event_id
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'days_before' => 'required|integer',
            'event_id' => 'required|integer'
        ]);
        $alert = new Alert();
        $alert->event_id = $request->event_id;
        $alert->days_before = $request->days_before;
        $alert->user_id = \Auth::user()->id;
        $alert->save();
        return response()->json([
            'id'           => $alert->id,
            'event'        => $alert->event->title,
            'date'         => $alert->date,
            'days_before'  => $alert->days_before,
            'delete_route' => route('alertes.destroy', ['alertes'=>$alert->id])]);
    }

    public function destroy(Request $request, $id)
    {
        if ($request->user() == Auth::user()) {
            Alert::destroy($id);
        }
        return Redirect::to('alertes/');
    }
}

resources/views/alerts/index.blade.php
@extends('master')

@section('title')
    Vos alertes
@endsection

@section('content')
    <main>
        <div class="row">
            <div class="columns small-12 center-block center float-none">
                @include('alerts.table')
            </div>
        </div>
    </main>
@endsection

@section('scripts')
    <script type="application/javascript" src="{{ asset('js/alerts.js') }}"></script>
@endsection

resources/views/alerts/table.blade.php
<table class="table-hover center-block center" id="tableAlerts">
    <thead>
    <tr>
        <td>Événement</td>
        <td>Date</td>
        <td></td>
    </tr>
    </thead>
    <tbody id="alerts">
    @foreach($alerts as $alert)
        <tr>
            <td>{{ $alert->event->title }}</td>
            <td>{{ $alert->date }} ({{ $alert->days_before }} jours avant)</td>
            <td>
                {!! Form::open(['route' => ['alertes.destroy', $alert->id], 'method' => 'delete']) !!}
                    {{ csrf_field() }}
                    <button type="submit" class="button alert">Supprimer</button>
                
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    <tr id="rowAddHidden" hidden>
        <td>
            <select name="event_id">
                <option disabled selected>Sélectionner un événement</option>
                @foreach(\App\Event::actives() as $event)
                    <option value="{{$event->id}}">{{$event->title}}</option>
                @endforeach
            </select>
        </td>
        <td>
            <input type="number" name="days_before" placeholder="Nombre de jours avant">
        </td>
        <td>
            <a class="button button-small alert-add" href="{{ route('alertes.store') }}">Ajouter</a>
            <a class="button button-small alert-cancel" href="#">Annuler</a>
        </td>
    </tr>
    </tbody>
    <tfoot>
    <tr id="newAlert">
        <td colspan="4">
            <a href="#" id="addAlert" class="button button-small">Nouvelle alerte</a>
        </td>
    </tr>
    </tfoot>
</table>
<meta name="csrf-token" content="{{ csrf_token() }}" property=""/>