app/Http/routes.php
<?php


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('auth/connexion', 'Auth\AuthController@getLogin');
Route::post('auth/connexion', 'Auth\AuthController@postLogin');
Route::get('auth/deconnexion', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/inscription', 'Auth\AuthController@getRegister');
Route::post('auth/inscription', 'Auth\AuthController@postRegister');


// Users route
Route::get('/api/users', 'AccountController@getUsers');
Route::get('/api/evenements/titles', 'EventsController@getTitles');
Route::get('/api/evenements', 'EventsController@getEventsSortByStatus');

// Account routes...
Route::get('/account', 'AccountController@edit')->middleware('auth');
Route::post('/account/{user}', 'AccountController@update')->middleware('auth');
Route::delete('/account/{id}', 'AccountController@destroy')->middleware('auth');

Route::get('/', 'PagesController@index');

Route::get('/evenements', 'EventsController@index');
Route::get('/evenements/recherche_avancee', 'EventsController@advancedSearch');
Route::post('/evenements/rechercher', 'EventsController@search');
Route::get('/evenements/rechercher/tag/{tag}', 'EventsController@searchByTag');
Route::get('/evenements/titles', 'EventsController@getTitles');

Route::get('/evenements/agenda', 'EventsController@showAgenda');
Route::get('/evenements/ajouter', 'EventsController@create')->middleware('auth');
Route::get('/evenements/validates/{id}', 'EventsController@validatesEvent')->middleware('auth');
Route::post('/evenements/ajouter', 'EventsController@store')->name('events.store')->middleware('auth');
Route::get('/evenements/{id}', 'EventsController@show');
Route::get('/evenements/{id}/modifier', 'EventsController@edit')->middleware('auth');
Route::post('/evenements/{id}/modifier', 'EventsController@update')->middleware('auth')->name('events.update');
Route::get('/evenements/{id}/tags', 'EventsController@getTagsJson');

Route::get('/gpscoords', 'EventsController@eventsWithCoordinates');


Route::get('/admin', 'AdminController@index')->middleware('auth');
Route::get('/admin/users', 'AdminController@users')->middleware('auth');
Route::get('/admin/events', 'AdminController@events')->middleware('auth');

Route::get('/contact', 'PagesController@contact');
Route::get('/mentions-legales', 'PagesController@legalMentions');

/**
 * Security to avoid route crash for some defaults redirects
 */
Route::get('/home', function() {
    return redirect('/');
});

Route::get('/test_email', 'EmailTestController@index');

Route::resource('alertes', 'AlertsController', ['except' => ['show', 'create', 'update', 'edit']]);
Route::post('avis/add', 'OpinionsController@store')->name('opinion.store');
Route::get('alertes/table', 'AlertsController@getHtmlTableListingAlerts');

Route::get("/sitemap", function(){
    // create new sitemap object
    $sitemap = App::make("sitemap");

    // set cache key (string), duration in minutes (Carbon|Datetime|int), turn on/off (boolean)
    // by default cache is disabled
    $sitemap->setCache('laravel.sitemap', 180);

    // check if there is cached sitemap and build new only if is not
    if (!$sitemap->isCached())
    {
        // add item to the sitemap (url, date, priority, freq)
        $sitemap->add(url('/'), date('c'), '1.0', 'daily');
        $sitemap->add(url('/auth/connexion'), date('c'), '0.5', 'monthly');
        $sitemap->add(url('/auth/inscription'), date('c'), '0.5', 'monthly');
        $sitemap->add(url('/account'), date('c'), '0.7', 'monthly');
        $sitemap->add(url('/evenements'), date('c'), '1.0', 'monthly');
        $sitemap->add(url('/evenements/rechercher'), date('c'), '0.8', 'monthly');
        $sitemap->add(url('/evenements/recherche_avancee'), date('c'), '0.8', 'monthly');
        $sitemap->add(url('/evenements/agenda'), date('c'), '0.9', 'monthly');
        $sitemap->add(url('/evenements/ajouter'), date('c'), '0.7', 'monthly');
        $sitemap->add(url('/contact'), date('c'), '0.6', 'monthly');
        $sitemap->add(url('/mentions-legales'), date('c'), '0.5', 'monthly');

    }

    // show your sitemap (options: 'xml' (default), 'html', 'txt', 'ror-rss', 'ror-rdf')
    return $sitemap->render('xml');
});

app/Event.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = ['title', 'begin_date', 'end_date', 'subject',
        'begin_hour', 'end_hour', 'description', 'address',
        'presentation_video', 'presentation_picture', 'seating_capacity',
        'edition', 'content_link', 'language_id', 'website',
        'facebook_link', 'twitter_link', 'youtube_link'];

    protected $guarded = ['valid'];

    public static $validator = ['title' => 'required|unique:events|max:55',
        'address' => 'required',
        'subject' => 'required',
        'begin_date' => 'required|date',
        'end_date' => 'required|date',
        'content_link' => 'url',
        'website' => 'url',
        'facebook_link' => 'url',
        'twitter_link' => 'url',
        'youtube_link' => 'url',
        'mail' => 'email',
    ];
    public static $validatorUpdate;

    /**
     * Event constructor.
     */
    public function __construct()
    {
        parent::__construct();
        self::$validatorUpdate = self::$validator;
        self::$validatorUpdate['title'] = 'required|max:55';
    }

    public static function withTag($tagSearched)
    {
        $allEvents = self::all();
        $matchingEvents = new Collection;
        foreach($allEvents as $event) {
            if ($event->tags->contains('title', $tagSearched)) {
                $matchingEvents->add($event);
            }
        }
        return $matchingEvents;
    }



    public function tags()
    {
        return $this->belongsToMany('App\Tag')->withTimestamps();
    }

    public function prices()
    {
        return $this->hasMany('App\Price');
    }

    public function links()
    {
        return $this->hasMany('App\EventLink');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function language()
    {
        return $this->belongsTo('App\Language');
    }

    /**
     * Gets all the opinions of the event
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function opinion()
    {
        return $this->hasMany('App\Opinion');
    }

    public static function getNext()
    {
        $nextDate = Event::where('begin_date', '>', Carbon::today()->toDateString())->where('valid', '1')->min('begin_date');
        return Event::where('begin_date', $nextDate)->first();
    }

    /**
     * Gets the current best evenement (with the best average note)
     * @return \App\Event
     */
    public static function getBest()
    {
        $eventsNotesArray = Event::actives()->pluck('average_note', 'id')->toArray();
        $bestEventId = array_keys($eventsNotesArray, max($eventsNotesArray))[0];

        return Event::find($bestEventId);
    }

    public static function actives()
    {
        return Event::where('valid', 1)->get();
    }

    /**
     * Gets the average note of an event, and returns this note or -1 if there is no note
     * @return float|int
     */
    public function getAverageNoteAttribute()
    {
        $sum = 0;
        $opinionList = $this->opinion;
        $opinionSize = 0;
        if ($opinionList !== null) {
            foreach ($opinionList as $opinion) {
                $sum += $opinion->score;
                $opinionSize++;
            }
            if ($opinionSize > 0) {
                $mid = $sum / $opinionSize;
                return round($mid, 1);
            }
        }
        return -1;
    }

    public function getDateAsCSSClass()
    {
        $begin = $this->begin_date;
        $end = $this->end_date;

        $begin = explode("-", $begin);
        $end = explode("-", $end);
        $class = "";

        $class .= intval($begin[0]) . " " . $this->intToMonth(intval($begin[1])) . " " . intval($begin[2]);

        if ($begin[2] != $end[2]) {
            $begin = intval($begin[2]);
            $diff = intval($end[2]) - $begin;
            for($i = $begin; $i <= $begin + $diff; $i++) {
                $class .= " " . $i ;
            }
        }

        return $class;

    }

    public function isOnManyDate()
    {
        return ($this->end_date != null && $this->end_date != $this->begin_date);
    }

    public function getShortDescriptionAttribute()
    {
        $descriptions = explode(" ", $this->description);
        $first_words = implode(" ", array_splice($descriptions, 0, 40));

        if (strlen(implode(" ", array_splice($descriptions, 40))) != 0)
            $first_words .= " ...";

        return $first_words;
    }

    private function intToMonth($value)
    {
        switch ($value) {
            case 1:
                return "Janvier";
            case 2:
                return "Fevrier";
            case 3:
                return "Mars";
            case 4:
                return "Avril";
            case 5:
                return "Mai";
            case 6:
                return "Juin";
            case 7:
                return "Juillet";
            case 8:
                return "Août";
            case 9:
                return "Septembre";
            case 10:
                return "Octobre";
            case 11:
                return "Novembre";
            case 12:
                return "Décembre";
            default:
                return "Error";
        }
    }

    public function getBeginDateCarbonAttribute()
    {
        return Carbon::parse($this->begin_date);
    }
    public function getEndDateCarbonAttribute()
    {
        return Carbon::parse($this->end_date);
    }

    public function getDatesForHumans()
    {
        if ($this->begin_date != $this->end_date) {
            return $this->begin_date_carbon->formatLocalized("%d %B %Y").' au '.$this->end_date_carbon->formatLocalized("%d %B %Y");
        }
        else {
            return $this->begin_date_carbon->formatLocalized("%d %B %Y");
        }
    }

    public static function getFromQuery($query)
    {
        return Event::where('title', 'LIKE', '%'.$query.'%')
            ->orWhere('description', 'LIKE', '%'.$query.'%')
            ->orWhere('address', 'LIKE', '%'.$query.'%')
            ->get();
    }

    public static function getFromParameters($title, $date, $address)
    {
        $events = Event::where('valid', '1');

        if (!empty($title)) {
            $events = $events->where('title', 'LIKE', '%'.$title.'%');
        }
        if (!empty($date)) {
            $events = $events->where('begin_date', '<=', $date)->where('end_date', '>=', $date);
        }
        if (!empty($address)) {
            $events = $events->where('address', 'LIKE', '%'.$address.'%');
        }
        return $events->get();
    }

    public function getPresentationVideoIframeAttribute()
    {
        return str_replace('watch?v=', 'v/', $this->presentation_video);
    }

    public function deletePrices()
    {
        foreach ($this->prices as $price) {
            $price->delete();
        }
    }

    public function deleteTags()
    {
        foreach ($this->prices as $price) {
            $price->delete();
        }
    }
}

resources/views/event/events.blade.php
@extends('master')

@section('title')
    Tous les événements
@endsection


@section('content')

    <main>
        <h1>Tous les événements</h1>
        <div id="search" class="row">
            <aside class="medium-12 columns">
                <form class="panel" method="get" action="{{ url('evenements/recherche_avancee') }}">
                    {{ csrf_field() }}
                    <h3>Affiner la recherche</h3>
                    <div class="row">
                        <div class="large-3 columns text-center">
                            <label for="title">Titre :</label>
                            <input type="text" name="title" id="title" value="{{ isset($input)? $input['title']:''  }}">
                        </div>
                        <div class="large-3 columns text-center">
                            <label for="date">Prochaine date programmée :</label>
                            <input type="date" name="date" id="date" value="{{ isset($input)? $input['date']:''  }}">
                        </div>
                        <div class="large-3 columns text-center">
                            <label for="address">Adresse :</label>
                            <input type="text" name="address" id="address" value="{{ isset($input)? $input['address']:''  }}">
                        </div>
                        <div class="large-3 columns text-center">
                            <input type="submit" class="button" value="Affiner la recherche">
                        </div>
                    </div>
                </form>
            </aside>
        </div>

        <div class="row catalogue">
            <section class="medium-12 columns">
                <div class="row">
                    @foreach($events as $event)
                        <div class="small-12 medium-6 large-4 end columns">
                            <div class="panel conf-medium-panel" data-href="{{url('evenements/'.$event->id)}}">
                                @include('event/medium', array('event' => $event))
                            </div>
                        </div>
                    @endforeach
                </div>
            </section>
        </div>
    </main>
    <a id="map-anchor" href="#" data-reveal-id="mapModal" title="Événements sur la carte">
        <img src="{{ asset('img/ico_map_france.png') }}" draggable="false" alt="Icone carte de France"/>
    </a>
    <div id="mapModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
        <h2 id="modalTitle">Tous les événements sur la carte</h2>
        <a class="close-reveal-modal" aria-label="Fermer">&#215;</a>
        <div id="map"></div>
    </div>
@endsection

@section('scripts')
    <script type="application/javascript">
        var urlCoords = '{{ url('gpscoords') }}';
    </script>
    <script type="application/javascript" src="{{ asset('js/google-maps-api.js') }}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ env('MAPS_SERVER_KEY', 'AIzaSyDl9nbwgZyE5J53whoOIItZBFNHBMv91Zc') }}&callback=initMap"></script>
@endsection

resources/views/event/large.blade.php
<div class="row">
    @if(!empty($event->presentation_picture))
    <div class="large-12 columns">
        <img src="{{ asset('img/pictures/normal/'.$event->presentation_picture) }}" alt="presentation_picture">
    </div>
    <hr />
    @endif
    <div class="large-6 columns">
        <h3>{{ $event->title }}</h3>
        <p>
            {{ $event->short_description }}
        </p>
    </div>
    <div class="large-6 columns no-padding">
        <div class="row">
            @if($event->average_note != -1)
            <div class="small-12 large-12 columns text-center">
                <div class="note-{{round($event->average_note)}} small inline-block" title="Note de l'événement">
                    <sup>{{ $event->average_note }}</sup>&frasl;<sub>6</sub>
                </div>
            </div>
            @endif
            <div class="small-6 large-12 columns no-padding">
                <p>
                    <img src="{{ asset('img/ico_calendrier.png') }}" alt="Icone calendrier">
                    {{ $event->getDatesForHumans() }}
                </p>
            </div>
            <div class="small-6 large-12 columns no-padding">
                <p>
                    <img src="{{ asset('img/ico_localisation.png') }}" alt="Icone localisation">
                    {{ $event->address }}
                </p>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <a href="{{ 'evenements/' . $event->id }}" class="button button-small">Plus de détails</a>
</div>

resources/views/event/medium.blade.php
<div class="row" id="{{ $event->html_id }}">
    <div class="large-12 columns text-center">
        <h3>{{ $event->title }}</h3>
    </div>

    <div class="large-12 columns text-center">
        <div class="row">
            @if(!empty($event->presentation_picture))
            <div class="large-8 columns text-center">
                <img src="{{ asset('img/pictures/normal/'.$event->presentation_picture) }}" alt="presentation_picture">
            </div>
            @endif
            @if($event->average_note != -1)
            <div class="large-4 columns text-center">
                <div class="note-{{round($event->average_note)}} small inline-block" title="Note de la conférence">
                    <sup>{{ $event->average_note }}</sup>&frasl;<sub>6</sub>
                </div>
            </div>
            @endif
        </div>
    </div>
    <div class="large-12 columns">
        <div class="row">
            <div class="small-12 large-12 columns">
                <p>
                    <img src="{{ asset('img/ico_calendrier.png') }}" alt="Icone calendrier">
                    {{ $event->getDatesForHumans() }}
                </p>
                <p>
                    <img src="{{ asset('img/ico_localisation.png') }}" alt="Icone localisation"> {{ $event->address }}
                </p>
            </div>
        </div>
    </div>
</div>
<div class="text-center">
    <a href="{{ 'evenements/'.$event->id }}" class="button button-small">Plus de détails</a>
</div>